In [ ]:
import os
import cv2
import natsort
from LabStretching import lab_stretching
from RGBStretching import rgb_stretching


def process_images(input_folder, output_folder, num_images=100):
    files = os.listdir(input_folder)
    files = natsort.natsorted(files)

    for file in files[:num_images]:
        input_path = os.path.join(input_folder, file)
        if os.path.isfile(input_path):
            img = cv2.imread(input_path)

            img = rgb_stretching(img)
            img = lab_stretching(img)

            output_path = os.path.join(output_folder, file)
            cv2.imwrite(output_path, img)


if __name__ == "__main__":
    input_folder = "./Dataset/raw-890"
    output_folder = "./OutputImages"
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    process_images(
        input_folder, output_folder, num_images=100
    )  # Process for num_images

PSNR

- more the better


In [1]:
import os
import cv2
from sewar import full_ref


# Method 1: using sewar library
def main(processed_folder, ground_reference):
    processed_images = os.listdir(processed_folder)
    total_psnr = 0
    num_images = 0
    for processed_image in processed_images:
        processed_path = os.path.join(processed_folder, processed_image)
        reference_path = os.path.join(ground_reference, processed_image)
        # print(processed_path)
        # print(reference_path)
        processed_img = cv2.imread(processed_path)
        reference_img = cv2.imread(reference_path)
        psnr = full_ref.psnr(reference_img, processed_img, MAX=None)
        total_psnr += psnr
        num_images += 1
        print(f"PSNR for {processed_image}: {psnr:.2f}")

    overall_psnr = total_psnr / num_images
    print(f"Overall PSNR: {overall_psnr:.2f}")


if __name__ == "__main__":
    processed_folder = "./OutputImages"
    ground_reference = "./Dataset/reference-890"
    main(processed_folder, ground_reference)

PSNR for 100_img_.png: 15.78
PSNR for 101_img_.png: 19.93
PSNR for 102_img_.png: 15.00
PSNR for 104_img_.png: 18.56
PSNR for 105_img_.png: 15.86
PSNR for 106_img_.png: 29.99
PSNR for 107_img_.png: 17.02
PSNR for 108_img_.png: 31.22
PSNR for 109_img_.png: 13.01
PSNR for 10_img_.png: 11.07
PSNR for 111_img_.png: 18.46
PSNR for 112_img_.png: 19.30
PSNR for 113_img_.png: 17.27
PSNR for 114_img_.png: 12.90
PSNR for 115_img_.png: 20.32
PSNR for 116_img_.png: 15.89
PSNR for 117_img_.png: 20.58
PSNR for 118_img_.png: 24.30
PSNR for 11_img_.png: 25.24
PSNR for 120_img_.png: 18.97
PSNR for 121_img_.png: 21.47
PSNR for 122_img_.png: 21.93
PSNR for 123_img_.png: 22.15
PSNR for 124_img_.png: 25.62
PSNR for 13_img_.png: 21.71
PSNR for 14_img_.png: 18.09
PSNR for 15_img_.png: 19.33
PSNR for 16_img_.png: 17.40
PSNR for 17_img_.png: 18.30
PSNR for 18_img_.png: 13.52
PSNR for 19_img_.png: 14.94
PSNR for 20.png: 21.00
PSNR for 22_img_.png: 19.39
PSNR for 23_img_.png: 20.29
PSNR for 24_img_.png: 18.96
PSN

In [2]:
from skimage.metrics import peak_signal_noise_ratio
import cv2
import os


# Method 2: Skimage library
def main(processed_folder, ground_reference):
    processed_images = os.listdir(processed_folder)
    total_psnr = 0
    num_images = 0
    for processed_image in processed_images:
        processed_path = os.path.join(processed_folder, processed_image)
        reference_path = os.path.join(ground_reference, processed_image)
        # print(processed_path)
        # print(reference_path)
        processed_img = cv2.imread(processed_path)
        reference_img = cv2.imread(reference_path)
        psnr = peak_signal_noise_ratio(reference_img, processed_img)
        total_psnr += psnr
        num_images += 1
        print(f"PSNR for {processed_image}: {psnr:.2f}")

    overall_psnr = total_psnr / num_images
    print(f"Overall PSNR: {overall_psnr:.2f}")


if __name__ == "__main__":
    processed_folder = "./OutputImages"
    ground_reference = "./Dataset/reference-890"
    main(processed_folder, ground_reference)

PSNR for 100_img_.png: 15.78
PSNR for 101_img_.png: 19.93
PSNR for 102_img_.png: 15.00
PSNR for 104_img_.png: 18.56
PSNR for 105_img_.png: 15.86
PSNR for 106_img_.png: 29.99
PSNR for 107_img_.png: 17.02
PSNR for 108_img_.png: 31.22
PSNR for 109_img_.png: 13.01
PSNR for 10_img_.png: 11.07
PSNR for 111_img_.png: 18.46
PSNR for 112_img_.png: 19.30
PSNR for 113_img_.png: 17.27
PSNR for 114_img_.png: 12.90
PSNR for 115_img_.png: 20.32
PSNR for 116_img_.png: 15.89
PSNR for 117_img_.png: 20.58
PSNR for 118_img_.png: 24.30
PSNR for 11_img_.png: 25.24
PSNR for 120_img_.png: 18.97
PSNR for 121_img_.png: 21.47
PSNR for 122_img_.png: 21.93
PSNR for 123_img_.png: 22.15
PSNR for 124_img_.png: 25.62
PSNR for 13_img_.png: 21.71
PSNR for 14_img_.png: 18.09
PSNR for 15_img_.png: 19.33
PSNR for 16_img_.png: 17.40
PSNR for 17_img_.png: 18.30
PSNR for 18_img_.png: 13.52
PSNR for 19_img_.png: 14.94
PSNR for 20.png: 21.00
PSNR for 22_img_.png: 19.39
PSNR for 23_img_.png: 20.29
PSNR for 24_img_.png: 18.96
PSN

In [3]:
# using formula
# reference https://medium.com/@jaikochhar06/how-to-evaluate-image-quality-in-python-a-comprehensive-guide-e486a0aa1f60#:~:text=The%20following%204%20evaluation%20metrics,Spectral%20Angle%20Mapper%20(SAM)

import os



import cv2


import numpy as np



def getPSNR(I1, I2):

    s1 = cv2.absdiff(I1, I2)

    s1 = np.float32(s1)

    s1 = s1 * s1
    sse = s1.sum()


    if sse <= 1e-10:

        return 0
    else:

        shape = I1.shape

        mse = 1.0 * sse / (shape[0] * shape[1] * shape[2])


        psnr = 10.0 * np.log10((255 * 255) / mse)
        return psnr



def main(processed_folder, ground_reference):
    processed_images = os.listdir(processed_folder)
    total_psnr = 0
    num_images = 0


    for processed_image in processed_images:

        processed_path = os.path.join(processed_folder, processed_image)

        reference_path = os.path.join(ground_reference, processed_image)

        processed_img = cv2.imread(processed_path)

        reference_img = cv2.imread(reference_path)


        psnr = getPSNR(reference_img, processed_img)

        total_psnr += psnr

        num_images += 1


        # print(f"PSNR for {processed_image}: {psnr:.2f}")

    overall_psnr = total_psnr / num_images

    print(f"Overall PSNR: {overall_psnr:.2f}")



if __name__ == "__main__":


    processed_folder = "./OutputImages"
    ground_reference = "./Dataset/reference-890"
    main(processed_folder, ground_reference)

Overall PSNR: 19.49


SSIM
Same image: ouput=1
Totally different image output=0


In [4]:
from skimage.metrics import structural_similarity as ssim
import cv2
import os


def main(processed_folder, ground_reference):
    processed_images = os.listdir(processed_folder)
    total_ssim = 0
    num_images = 0
    for processed_image in processed_images:
        processed_path = os.path.join(processed_folder, processed_image)
        reference_path = os.path.join(ground_reference, processed_image)
        # print(processed_path)
        # print(reference_path)
        processed_img = cv2.imread(processed_path)
        reference_img = cv2.imread(reference_path)
        ssim_value = ssim(reference_img, processed_img, channel_axis=2)
        total_ssim += ssim_value
        num_images += 1
        print(f"SSIM for {processed_image}: {ssim_value:.4f}")

    overall_ssim = total_ssim / num_images
    print(f"Overall SSIM: {overall_ssim:.4f}")


if __name__ == "__main__":
    processed_folder = "./OutputImages"
    ground_reference = "./Dataset/reference-890"
    main(processed_folder, ground_reference)

SSIM for 100_img_.png: 0.7994
SSIM for 101_img_.png: 0.8904
SSIM for 102_img_.png: 0.7509
SSIM for 104_img_.png: 0.7510
SSIM for 105_img_.png: 0.7763
SSIM for 106_img_.png: 0.9402
SSIM for 107_img_.png: 0.6635
SSIM for 108_img_.png: 0.9780
SSIM for 109_img_.png: 0.6695
SSIM for 10_img_.png: 0.5591
SSIM for 111_img_.png: 0.6333
SSIM for 112_img_.png: 0.8673
SSIM for 113_img_.png: 0.6494
SSIM for 114_img_.png: 0.6020
SSIM for 115_img_.png: 0.8720
SSIM for 116_img_.png: 0.7868
SSIM for 117_img_.png: 0.9057
SSIM for 118_img_.png: 0.9200
SSIM for 11_img_.png: 0.8034
SSIM for 120_img_.png: 0.8137
SSIM for 121_img_.png: 0.8810
SSIM for 122_img_.png: 0.8865
SSIM for 123_img_.png: 0.9380
SSIM for 124_img_.png: 0.9011
SSIM for 13_img_.png: 0.8245
SSIM for 14_img_.png: 0.7601
SSIM for 15_img_.png: 0.7571
SSIM for 16_img_.png: 0.7843
SSIM for 17_img_.png: 0.8476
SSIM for 18_img_.png: 0.6880
SSIM for 19_img_.png: 0.6781
SSIM for 20.png: 0.8934
SSIM for 22_img_.png: 0.8529
SSIM for 23_img_.png: 0.88

In [5]:
from skimage.metrics import structural_similarity as ssim
import cv2

img1 = cv2.imread("./OutputImages/97_img_.png")
img2 = cv2.imread("./OutputImages/97_img_.png")
ssim_score, mapped = ssim(img1, img2, full=True, channel_axis=2)
print(ssim_score)
print(mapped)

1.0
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
